/**
 * Sprint 3 K1: seed and normalize AI video tools.
 * 运行：npm run seed:video-tools
 */
import { config } from 'dotenv';
import { db } from '@/lib/db';
import { tools } from '@/lib/db/schema';

config({ path: '.env.local' });

type VideoTool = Omit<typeof tools.$inferInsert, 'publishedAt'> & {
  publishedAt?: string;
};

const TODAY = new Date().toISOString().slice(0, 10);
const NOW = new Date();

const VIDEO_TOOLS: VideoTool[] = [
  {
    id: 'luma-dream-machine',
    name: 'Luma Dream Machine',
    mono: 'LD',
    brand: '#111827',
    catId: 'video',
    en: 'Luma AI video and image creation platform with Dream Machine, Ray video models, references, boards, and commercial plans.',
    zh: 'Luma AI 推出的视频与图像创作平台，支持 Dream Machine、Ray 视频模型、参考图、创意看板和商业授权套餐。',
    pricing: 'Freemium',
    url: 'https://lumalabs.ai',
    chinaAccess: 'accessible',
    chineseUi: false,
    freeQuota: '提供试用额度，具体以官方 plans 为准',
    apiAvailable: true,
    features: ['文生视频', '图生视频', '参考图控制', '创意看板'],
    registerMethod: ['邮箱', 'Google/Apple'],
    needsOverseasPhone: false,
    needsRealName: false,
    overseasPaymentOnly: true,
    priceCny: 'Plus $30/月起，Pro $90/月起；以 Luma 官方 pricing 为准',
    appStoreCn: false,
    cnAlternatives: ['kling-ai', 'hailuo-ai', 'jimeng-ai'],
    howToUse: [
      '访问 lumalabs.ai 注册账号',
      '选择图像或视频生成入口',
      '输入提示词，可加入参考图和风格要求',
      '生成后下载或继续在看板中迭代',
    ],
    faqs: [
      { q: 'Luma 国内可以直接用吗？', a: '官网可访问性会受网络环境影响，付费通常依赖海外支付方式，建议先用免费试用额度验证。' },
      { q: 'Luma 有 API 吗？', a: '有，Luma 提供 Dream Machine / UNI 相关 API 与开发者文档，具体价格和可用模型以官方页面为准。' },
    ],
  },
  {
    id: 'vidu-ai',
    name: 'Vidu AI',
    mono: 'VD',
    brand: '#111827',
    catId: 'video',
    en: 'AI video generator supporting text-to-video, image-to-video, start-end video, references, templates, and API credits.',
    zh: 'AI 视频生成工具，支持文生视频、图生视频、首尾帧视频、多参考一致性、模板和 API 点数计费。',
    pricing: 'Freemium',
    url: 'https://www.vidu.com',
    chinaAccess: 'accessible',
    chineseUi: false,
    freeQuota: '有免费与订阅计划，API 按 credits 计费',
    apiAvailable: true,
    features: ['文生视频', '图生视频', '首尾帧视频', '多参考一致性'],
    registerMethod: ['邮箱', 'Google'],
    needsOverseasPhone: false,
    needsRealName: false,
    overseasPaymentOnly: true,
    priceCny: '订阅经 Stripe；API credits $0.005/credit，以 Vidu 官方 pricing 为准',
    appStoreCn: false,
    cnAlternatives: ['kling-ai', 'hailuo-ai', 'jimeng-ai'],
    howToUse: [
      '访问 vidu.com 注册账号',
      '选择文生视频、图生视频或参考图模式',
      '设置时长、分辨率和参考素材',
      '生成后预览、下载或继续编辑',
    ],
    faqs: [
      { q: 'Vidu 支持哪些视频模式？', a: '官方 pricing/API 文档列出 text2video、img2video、start-end2video 等模式，具体以当前模型说明为准。' },
      { q: 'Vidu 付费方式是什么？', a: '订阅通过 Stripe，API 以 credits 消耗计费；国内支付便利性需实际账号验证。' },
    ],
  },
  {
    id: 'higgsfield-ai',
    name: 'Higgsfield AI',
    mono: 'HF',
    brand: '#111827',
    catId: 'video',
    en: 'AI creative workspace for cinematic social videos, ads, image and video generation, motion control, and marketing studio workflows.',
    zh: '面向短视频、广告和社媒创意的 AI 影像工作台，支持图像/视频生成、动作控制、营销工作流和多模型生成。',
    pricing: 'Freemium',
    url: 'https://higgsfield.ai',
    chinaAccess: 'accessible',
    chineseUi: false,
    freeQuota: '有免费入口，套餐和 credits 以官网为准',
    apiAvailable: false,
    features: ['视频生成', '动作控制', '广告创意', '多模型工作区'],
    registerMethod: ['邮箱', 'Google/Apple'],
    needsOverseasPhone: false,
    needsRealName: false,
    overseasPaymentOnly: true,
    priceCny: '套餐和 credits 以 Higgsfield 官方页面为准',
    appStoreCn: false,
    cnAlternatives: ['kling-ai', 'hailuo-ai', 'jimeng-ai'],
    howToUse: [
      '访问 higgsfield.ai 注册账号',
      '选择 Create Video 或 Marketing Studio',
      '输入创意目标、产品链接或参考图',
      '用预设镜头、动作控制和多模型生成视频',
    ],
    faqs: [
      { q: 'Higgsfield 更适合什么场景？', a: '更偏短视频、广告、UGC 和社媒创意工作流，而不是单纯的文生视频工具。' },
      { q: 'Higgsfield 国内使用有什么限制？', a: '官网可访问性、支付和模型加载稳定性需要按具体网络环境验证；生产使用建议先小样本测试。' },
    ],
  },
  {
    id: 'hedra',
    name: 'Hedra',
    mono: 'HD',
    brand: '#111827',
    catId: 'digital-human',
    en: 'AI media creation platform focused on controllable character video, talking characters, image, video, and audio generation.',
    zh: '面向可控角色视频和数字人内容的 AI 创作平台，支持角色视频、口播人物、图像、视频和音频生成。',
    pricing: 'Freemium',
    url: 'https://www.hedra.com',
    chinaAccess: 'accessible',
    chineseUi: false,
    freeQuota: '有限免费水印生成，订阅和 credits 以官方 plans 为准',
    apiAvailable: false,
    features: ['角色视频', '口播数字人', '音视频生成', '多模型 credits'],
    registerMethod: ['邮箱', 'Google'],
    needsOverseasPhone: false,
    needsRealName: false,
    overseasPaymentOnly: true,
    priceCny: '按订阅和 credits 消耗，详见 Hedra 官方 plans',
    appStoreCn: false,
    cnAlternatives: ['kling-ai', 'hailuo-ai', 'jimeng-ai'],
    howToUse: [
      '访问 hedra.com 注册账号',
      '选择角色、图片或视频生成入口',
      '上传角色图或输入内容脚本',
      '选择模型并按 credits 生成视频',
    ],
    faqs: [
      { q: 'Hedra 和普通视频生成工具有什么区别？', a: 'Hedra 更强调可控角色、口播和数字人内容，适合人物驱动的短视频和营销素材。' },
      { q: 'Hedra 费用怎么计算？', a: '官方 plans 使用 credits 体系，不同视频模型按秒消耗不同 credits。' },
    ],
  },
  {
    id: 'runway',
    name: 'Runway Gen-4',
    mono: 'R',
    brand: '#111827',
    catId: 'video',
    en: 'AI video creation platform for text-to-video, image-to-video, video editing, motion and cinematic generation workflows.',
    zh: '面向创作者和团队的 AI 视频创作平台，支持文生视频、图生视频、视频编辑、镜头运动和电影感生成工作流。',
    pricing: 'Freemium',
    url: 'https://runwayml.com',
    chinaAccess: 'accessible',
    chineseUi: false,
    freeQuota: '有限免费点数',
    apiAvailable: true,
    features: ['文生视频', '图生视频', '视频编辑', '运动控制'],
    registerMethod: ['邮箱', 'Google/Apple'],
    needsOverseasPhone: false,
    needsRealName: false,
    overseasPaymentOnly: true,
    priceCny: '订阅和 credits 以 Runway 官方 pricing 为准',
    appStoreCn: false,
    cnAlternatives: ['kling-ai', 'hailuo-ai', 'jimeng-ai'],
  },
  {
    id: 'descript',
    name: 'Descript',
    mono: 'D',
    brand: '#111827',
    catId: 'video',
    en: 'AI-powered video and audio editing platform with text-based editing, transcription, dubbing, AI co-editor, and avatar tools.',
    zh: 'AI 视频和音频编辑平台，支持文本剪视频、转录、配音、AI 协同编辑、翻译和头像生成，适合播客和短视频后期。',
    pricing: 'Freemium',
    url: 'https://www.descript.com',
    chinaAccess: 'accessible',
    chineseUi: false,
    freeQuota: '有免费计划，付费版按月订阅',
    apiAvailable: false,
    features: ['文本剪视频', '转录字幕', 'AI 配音', '视频后期'],
    registerMethod: ['邮箱', 'Google'],
    needsOverseasPhone: false,
    needsRealName: false,
    overseasPaymentOnly: true,
    priceCny: 'Free 可用；Hobbyist $16/月起，Creator $24/月起，以 Descript 官方 pricing 为准',
    appStoreCn: false,
    cnAlternatives: ['jianying', 'jimeng-ai'],
    howToUse: [
      '访问 descript.com 注册账号',
      '上传音频或视频素材',
      '等待自动转录后像编辑文档一样剪辑',
      '使用 AI 工具生成字幕、配音或短片片段',
    ],
    faqs: [
      { q: 'Descript 是视频生成工具吗？', a: '它更偏 AI 视频/音频后期编辑，而不是纯文生视频；适合播客、访谈、课程和短视频剪辑。' },
      { q: 'Descript 国内使用有什么限制？', a: '官网可访问性会受网络环境影响，付费通常依赖海外支付方式。' },
    ],
  },
  {
    id: 'pixelle-video',
    name: 'Pixelle-Video',
    mono: 'PV',
    brand: '#111827',
    catId: 'video',
    en: 'Open-source text-to-video model project from AIDC-AI, suitable for research and developer experimentation rather than consumer production workflows.',
    zh: 'AIDC-AI 开源的视频生成模型项目，更适合研究和开发者实验，不是面向普通用户的一站式消费级视频产品。',
    pricing: 'Free',
    url: 'https://github.com/AIDC-AI/Pixelle-Video',
    chinaAccess: 'unknown',
    chineseUi: false,
    freeQuota: '开源项目免费，运行成本取决于本地或云端算力',
    apiAvailable: false,
    openSource: true,
    githubRepo: 'AIDC-AI/Pixelle-Video',
    features: ['开源模型', '文生视频', '研究实验', '本地部署'],
    registerMethod: ['GitHub'],
    needsOverseasPhone: false,
    needsRealName: false,
    overseasPaymentOnly: false,
    priceCny: '代码免费，GPU 算力和部署成本自理',
    appStoreCn: false,
    cnAlternatives: ['kling-ai', 'hailuo-ai', 'jimeng-ai'],
    howToUse: [
      '访问 GitHub 仓库查看模型说明',
      '按 README 准备 Python 和 GPU 环境',
      '下载模型权重和示例配置',
      '运行示例脚本生成视频样本',
    ],
    faqs: [
      { q: 'Pixelle-Video 适合普通用户吗？', a: '不太适合。它更像开源研究项目，需要本地环境和 GPU，普通用户建议先用可灵、海螺、即梦等产品。' },
      { q: 'Pixelle-Video 国内可用性怎么判断？', a: '它主要依赖 GitHub 和模型下载链路，实际可用性取决于代码仓库、权重下载和本地算力环境。' },
    ],
  },
  {
    id: 'sora',
    name: 'Sora',
    mono: 'So',
    brand: '#111827',
    catId: 'video',
    en: "OpenAI's video generation product for creating and remixing AI videos from prompts and media.",
    zh: 'OpenAI 推出的视频生成产品，可根据提示词和素材生成、混剪和重构 AI 视频，适合探索长视频与复杂镜头生成。',
    pricing: 'Paid',
    url: 'https://sora.com',
    chinaAccess: 'vpn-required',
    chineseUi: false,
    freeQuota: '无独立免费额度，随 OpenAI 账号和套餐变化',
    apiAvailable: true,
    features: ['视频生成', '视频 Remix', '复杂镜头', 'OpenAI 生态'],
    registerMethod: ['OpenAI 账号'],
    needsOverseasPhone: false,
    needsRealName: false,
    overseasPaymentOnly: true,
    priceCny: '随 OpenAI / Sora 官方套餐变化，通常需海外支付方式',
    appStoreCn: false,
    cnAlternatives: ['kling-ai', 'hailuo-ai', 'jimeng-ai'],
  },
  {
    id: 'pika',
    name: 'Pika',
    mono: 'PK',
    brand: '#111827',
    catId: 'video',
    en: 'AI video platform for text-to-video, image-to-video, effects, lip sync, and short creative video generation.',
    zh: 'AI 短视频生成平台，支持文生视频、图生视频、特效、口型同步和创意短片生成。',
    pricing: 'Freemium',
    url: 'https://pika.art',
    chinaAccess: 'accessible',
    chineseUi: false,
    freeQuota: '免费版可用',
    apiAvailable: false,
    features: ['文生视频', '图生视频', '视频特效', '口型同步'],
    registerMethod: ['邮箱', 'Google/Discord'],
    needsOverseasPhone: false,
    needsRealName: false,
    overseasPaymentOnly: true,
    priceCny: '订阅和 credits 以 Pika 官方 pricing 为准',
    appStoreCn: false,
    cnAlternatives: ['kling-ai', 'hailuo-ai', 'jimeng-ai'],
  },
  {
    id: 'jimeng-ai',
    name: '即梦AI',
    mono: '梦',
    brand: '#EC4899',
    catId: 'video',
    en: "ByteDance's Jimeng AI for image and video generation, integrated with CapCut and Chinese creator workflows.",
    zh: '字节跳动推出的 AI 创作平台，支持文字生成图片和视频，与剪映生态结合，适合中文创作者做短视频素材。',
    pricing: 'Freemium',
    url: 'https://jimeng.jianying.com',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '每日免费生成次数',
    apiAvailable: false,
    features: ['文生视频', '图生视频', '图片生成', '剪映生态'],
    registerMethod: ['抖音/剪映账号', '手机号'],
    needsOverseasPhone: false,
    needsRealName: false,
    overseasPaymentOnly: false,
    priceCny: '基础额度免费，高级能力和会员权益以即梦官方说明为准',
    appStoreCn: true,
    publicAccount: '即梦AI',
    howToUse: [
      '访问 jimeng.jianying.com 或使用即梦 App',
      '用抖音 / 剪映账号登录',
      '选择图片生成或视频生成功能',
      '生成后可继续导入剪映编辑',
    ],
  },
  {
    id: 'kling-ai',
    name: '可灵AI',
    mono: 'KL',
    brand: '#7C3AED',
    catId: 'video',
    en: "Kuaishou's Kling AI video generator supporting text-to-video, image-to-video, camera movement, and developer API.",
    zh: '快手推出的 AI 视频生成工具，支持文生视频、图生视频、首尾帧、运镜控制和开发者 API。',
    pricing: 'Freemium',
    url: 'https://klingai.com',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '每日免费生成次数',
    apiAvailable: true,
    features: ['文生视频', '图生视频', '首尾帧视频', '运镜控制'],
    registerMethod: ['手机号', '快手账号'],
    needsOverseasPhone: false,
    needsRealName: false,
    overseasPaymentOnly: false,
    priceCny: '基础额度免费，高级模型和会员权益以可灵官方说明为准',
    appStoreCn: true,
    publicAccount: '可灵AI',
    cnAlternatives: ['jimeng-ai', 'hailuo-ai'],
  },
  {
    id: 'hailuo-ai',
    name: '海螺AI',
    mono: '海',
    brand: '#0891B2',
    catId: 'video',
    en: "MiniMax's Hailuo AI for generating cinematic short videos from text and images.",
    zh: 'MiniMax 推出的 AI 视频生成工具，支持文生视频和图生视频，适合电影感短片、广告片和创意素材。',
    pricing: 'Freemium',
    url: 'https://hailuoai.com',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '每日免费生成次数',
    apiAvailable: false,
    features: ['文生视频', '图生视频', '电影感画面', '创意短片'],
    registerMethod: ['手机号', '邮箱'],
    needsOverseasPhone: false,
    needsRealName: false,
    overseasPaymentOnly: false,
    priceCny: '基础额度免费，高级模型和会员权益以海螺官方说明为准',
    appStoreCn: true,
    publicAccount: '海螺AI',
    cnAlternatives: ['kling-ai', 'jimeng-ai'],
  },
];

async function main() {
  let changed = 0;

  for (const tool of VIDEO_TOOLS) {
    const result = await db
      .insert(tools)
      .values({
        ...tool,
        pricingUpdatedAt: NOW,
        accessUpdatedAt: NOW,
        featuresUpdatedAt: NOW,
        complianceUpdatedAt: NOW,
        publishedAt: tool.publishedAt ?? TODAY,
      })
      .onConflictDoUpdate({
        target: tools.id,
        set: {
          name: tool.name,
          mono: tool.mono,
          brand: tool.brand,
          catId: tool.catId,
          en: tool.en,
          zh: tool.zh,
          pricing: tool.pricing,
          url: tool.url,
          chinaAccess: tool.chinaAccess,
          chineseUi: tool.chineseUi ?? false,
          freeQuota: tool.freeQuota,
          apiAvailable: tool.apiAvailable ?? false,
          openSource: tool.openSource ?? false,
          githubRepo: tool.githubRepo,
          features: tool.features,
          pricingDetail: tool.pricingDetail,
          alternatives: tool.alternatives,
          registerMethod: tool.registerMethod,
          needsOverseasPhone: tool.needsOverseasPhone ?? false,
          needsRealName: tool.needsRealName ?? false,
          overseasPaymentOnly: tool.overseasPaymentOnly ?? false,
          priceCny: tool.priceCny,
          miniProgram: tool.miniProgram,
          appStoreCn: tool.appStoreCn ?? false,
          publicAccount: tool.publicAccount,
          cnAlternatives: tool.cnAlternatives,
          tutorialLinks: tool.tutorialLinks,
          howToUse: tool.howToUse,
          faqs: tool.faqs,
          pricingUpdatedAt: NOW,
          accessUpdatedAt: NOW,
          featuresUpdatedAt: NOW,
          complianceUpdatedAt: NOW,
        },
      });

    if (result.rowCount && result.rowCount > 0) changed += result.rowCount;
    console.log(`ok ${tool.id}`);
  }

  console.log(`Done. Upserted ${changed} video tools.`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
