/**
 * 批量插入国内主流 AI 工具（及部分高知名度国际工具补充）
 * 运行：npm run seed:cn-tools
 */
import { db } from '@/lib/db';
import { tools } from '@/lib/db/schema';

const TODAY = new Date().toISOString().slice(0, 10);

const CN_TOOLS = [
  // ── 国内对话 AI ──────────────────────────────────────────────────────────
  {
    id: 'doubao',
    name: '豆包',
    mono: '豆',
    brand: '#4E6EF2',
    catId: 'chatbot',
    url: 'https://www.doubao.com',
    en: "ByteDance's all-in-one AI assistant for intelligent conversation, writing, image generation, PDF analysis, and custom AI agents.",
    zh: '字节跳动推出的全能AI助手，支持智能对话、文案创作、图片生成、PDF分析及自定义智能体，中文理解能力出众。',
    pricing: 'Freemium',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '每日免费使用',
    apiAvailable: false,
    featured: true,
    features: ['智能对话与问答', '文案创作与润色', 'AI图片生成', 'PDF/文档分析'],
    howToUse: [
      '访问 doubao.com 或下载豆包App（支持 iOS / Android / PC）',
      '用手机号或字节跳动账号注册登录',
      '在对话框输入问题或需求，可上传图片 / 文档',
      '探索「智能体」功能，使用或创建专属 AI 助手',
    ],
    faqs: [
      { q: '豆包完全免费吗？', a: '基础对话功能免费，高清图片生成等高级功能有次数限制。' },
      { q: '豆包支持上传文件吗？', a: '支持上传 PDF、Word、图片，可对内容进行问答和分析。' },
      { q: '国内可以直接访问吗？', a: '是的，无需 VPN，直接访问 doubao.com 或下载 App 即可。' },
    ],
  },
  {
    id: 'kimi',
    name: 'Kimi',
    mono: 'Ki',
    brand: '#6366F1',
    catId: 'chatbot',
    url: 'https://kimi.moonshot.cn',
    en: "Moonshot AI's long-context assistant specializing in reading ultra-long documents, web search, and deep reasoning.",
    zh: '月之暗面出品的长文本AI助手，支持200万字超长上下文，擅长文档分析、联网搜索和深度推理。',
    pricing: 'Freemium',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '每日免费额度',
    apiAvailable: true,
    featured: true,
    features: ['200万字超长上下文', '文档/PDF深度阅读', '联网实时搜索', '代码编写与调试'],
    howToUse: [
      '访问 kimi.moonshot.cn，用手机号注册登录',
      '可直接对话，也可上传 PDF / Word / 网页链接',
      '开启「联网搜索」模式获取实时信息',
      '开发者可申请 Moonshot API 接入',
    ],
    faqs: [
      { q: 'Kimi 的最大上下文是多少？', a: '支持最长 200 万 token，可一次性读取数百页长文档。' },
      { q: '可以同时上传多个文件吗？', a: '支持，并对全部内容进行联合分析和问答。' },
      { q: 'Kimi 有 API 吗？', a: '有，月之暗面提供 Moonshot API，访问 platform.moonshot.cn 申请。' },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    mono: 'DS',
    brand: '#1D4ED8',
    catId: 'chatbot',
    url: 'https://chat.deepseek.com',
    en: "DeepSeek's frontier AI with exceptional reasoning and coding, completely free with open-source model weights.",
    zh: '深度求索推出的顶级AI大模型，推理和编程能力媲美国际一流，完全免费，并开源了模型权重可本地部署。',
    pricing: 'Free',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '完全免费',
    apiAvailable: true,
    openSource: true,
    featured: true,
    features: ['顶级推理能力（R1模型）', '强大的代码生成', '完全免费无限制', '开源可本地部署'],
    howToUse: [
      '访问 chat.deepseek.com，用邮箱或手机号注册',
      '选择 DeepSeek-V3（通用）或 DeepSeek-R1（深度推理）',
      '直接对话，适用代码、数学、写作等所有场景',
      '开发者可通过 platform.deepseek.com 调用 API',
    ],
    faqs: [
      { q: 'DeepSeek 真的完全免费吗？', a: '网页版完全免费，API 按 token 计费，价格极低（约为 GPT-4 的 1/20）。' },
      { q: 'R1 和 V3 有什么区别？', a: 'V3 是通用对话模型，速度快；R1 是推理模型，会逐步思考，擅长数学和复杂问题。' },
      { q: '可以本地部署吗？', a: '可以，DeepSeek 开源了模型权重，通过 Ollama 等工具即可本地运行。' },
    ],
  },
  {
    id: 'wenxin-yiyan',
    name: '文心一言',
    mono: '文',
    brand: '#E11D48',
    catId: 'chatbot',
    url: 'https://yiyan.baidu.com',
    en: "Baidu's ERNIE Bot — powerful Chinese AI assistant for conversation, text generation, and multimodal tasks with real-time search.",
    zh: '百度推出的文心大模型AI助手，中文理解与创作能力强，集成百度搜索获取实时信息，支持多模态交互。',
    pricing: 'Freemium',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '每日免费使用',
    apiAvailable: true,
    features: ['中文写作与创作', '百度实时搜索联动', '图片生成（文心一格）', '插件与工具扩展'],
    howToUse: [
      '访问 yiyan.baidu.com，用百度账号登录',
      '在对话框输入问题，支持文字和图片输入',
      '使用「插件」功能扩展能力（数据分析、画图等）',
      '企业用户可申请文心一言 API 接入',
    ],
    faqs: [
      { q: '文心一言和文心一格有什么区别？', a: '文心一言是对话 AI 助手，文心一格是专注图片生成的绘画工具，均基于文心大模型。' },
      { q: '有 API 吗？', a: '有，百度智能云提供文心一言 API，在 cloud.baidu.com 申请。' },
    ],
  },
  {
    id: 'tongyi-qianwen',
    name: '通义千问',
    mono: '通',
    brand: '#F97316',
    catId: 'chatbot',
    url: 'https://tongyi.aliyun.com',
    en: "Alibaba's Qwen AI assistant with strong reasoning, coding, math, and document understanding, open-source models available.",
    zh: '阿里巴巴推出的通义千问AI助手，擅长推理、编程和数学，支持多轮对话和文档分析，开源版本可免费下载。',
    pricing: 'Freemium',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '每日免费使用',
    apiAvailable: true,
    openSource: true,
    features: ['强大的推理与数学能力', '代码生成与调试', '长文档理解分析', '阿里云生态深度集成'],
    howToUse: [
      '访问 tongyi.aliyun.com，用阿里云 / 淘宝账号登录',
      '选择对话模式，直接输入问题或上传文档',
      '使用通义灵码插件（VS Code）获得 AI 编程辅助',
      '开发者可通过阿里云 DashScope API 调用 Qwen 模型',
    ],
    faqs: [
      { q: '通义千问有开源版本吗？', a: '有，阿里开源了 Qwen 系列模型，可在 HuggingFace 和 ModelScope 下载。' },
      { q: '有专门的编程助手吗？', a: '有，通义灵码是阿里推出的 AI 编程工具，提供 VS Code / JetBrains 插件。' },
    ],
  },
  {
    id: 'zhipu-chatglm',
    name: '智谱清言',
    mono: '智',
    brand: '#0D9488',
    catId: 'chatbot',
    url: 'https://chatglm.cn',
    en: "Zhipu AI's ChatGLM assistant with natural Chinese dialogue, AI drawing, code generation, and open GLM-4 API.",
    zh: '清华系智谱AI推出的AI助手，基于 ChatGLM 大模型，中文表达自然流畅，支持 AI 绘图、代码和文件分析。',
    pricing: 'Freemium',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '每日免费使用',
    apiAvailable: true,
    features: ['自然流畅的中文对话', 'AI绘图（CogView）', '代码生成与解释', 'GLM-4 开放 API'],
    howToUse: [
      '访问 chatglm.cn，手机号注册登录',
      '选择对话、绘图或文件分析功能',
      '上传文档进行问答或总结',
      '开发者可在 bigmodel.cn 申请 GLM API',
    ],
    faqs: [
      { q: '智谱清言和 ChatGLM 是什么关系？', a: '智谱清言是面向用户的产品，ChatGLM 是底层开源大模型，由清华大学和智谱 AI 联合开发。' },
      { q: '有 API 吗？', a: '有，通过 BigModel 平台（bigmodel.cn）提供 GLM-4 等模型的 API 服务。' },
    ],
  },
  {
    id: 'xunfei-spark',
    name: '讯飞星火',
    mono: '火',
    brand: '#2563EB',
    catId: 'chatbot',
    url: 'https://xinghuo.xfyun.cn',
    en: "iFlytek's Spark AI assistant with industry-leading voice interaction and strong Chinese language processing for education and office use.",
    zh: '科大讯飞推出的星火大模型AI助手，语音交互能力业界领先，在教育、办公场景有深度优化。',
    pricing: 'Freemium',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '每日免费额度',
    apiAvailable: true,
    features: ['领先的语音交互能力', '教育场景专项优化', '文档写作与辅助', 'PPT自动生成'],
    howToUse: [
      '访问 xinghuo.xfyun.cn，注册讯飞账号',
      '选择文字对话或语音交互模式',
      '上传文档或直接对话完成写作任务',
      '开发者可在 console.xfyun.cn 申请 Spark API',
    ],
    faqs: [
      { q: '讯飞星火在教育方面有何优势？', a: '深耕教育 AI 多年，在作文批改、英语学习、题目解析等教育场景有专项优化。' },
      { q: '支持语音输入吗？', a: '支持，科大讯飞的语音识别技术行业领先，语音转文字准确率极高。' },
    ],
  },
  {
    id: 'tencent-yuanbao',
    name: '腾讯元宝',
    mono: '元',
    brand: '#059669',
    catId: 'chatbot',
    url: 'https://yuanbao.tencent.com',
    en: "Tencent's Yuanbao AI assistant powered by Hunyuan model with WeChat ecosystem integration, web search, and file analysis.",
    zh: '腾讯推出的AI助手，基于混元大模型，深度整合微信生态，支持联网搜索、文件分析和智能问答，完全免费。',
    pricing: 'Free',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '完全免费',
    apiAvailable: false,
    features: ['混元大模型驱动', '微信生态深度整合', '联网实时搜索', '文件上传与分析'],
    howToUse: [
      '访问 yuanbao.tencent.com 或微信搜索「元宝」小程序',
      '用微信扫码或 QQ 账号登录',
      '直接输入问题，可开启联网搜索获取最新信息',
      '上传文件（PDF / Word / 图片）进行智能分析',
    ],
    faqs: [
      { q: '腾讯元宝完全免费吗？', a: '目前完全免费，无使用次数限制。' },
      { q: '元宝和腾讯混元有什么关系？', a: '腾讯元宝是面向用户的产品名，混元是底层大模型名称。' },
    ],
  },
  {
    id: 'tiangong-ai',
    name: '天工AI',
    mono: '天',
    brand: '#CA8A04',
    catId: 'chatbot',
    url: 'https://www.tiangong.cn',
    en: "Kunlun Tech's Tiangong AI with integrated search, dialogue, long-form writing, and image generation.",
    zh: '昆仑万维推出的天工AI助手，集搜索、对话、长文写作和图片生成于一体，支持联网获取最新信息。',
    pricing: 'Freemium',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '每日免费使用',
    apiAvailable: false,
    features: ['联网AI搜索', '长文写作辅助', 'AI图片生成', '多模态理解'],
    howToUse: [
      '访问 tiangong.cn，手机号注册登录',
      '选择对话、搜索或创作模式',
      '开启联网模式可获取实时信息',
      '使用 AI 写作功能生成文章或报告',
    ],
    faqs: [
      { q: '天工AI有哪些特色功能？', a: '擅长长文写作和联网搜索，提供专属搜索引擎模式，适合内容创作者。' },
    ],
  },
  {
    id: 'metaso',
    name: '秘塔AI搜索',
    mono: '搜',
    brand: '#475569',
    catId: 'ai-search',
    url: 'https://metaso.cn',
    en: "Ad-free AI search engine that delivers source-cited comprehensive answers across web, academic, and social media.",
    zh: '无广告的AI搜索引擎，自动汇总多方来源并生成带引用的答案，支持学术、新闻、社交媒体多场景搜索。',
    pricing: 'Free',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '完全免费',
    apiAvailable: false,
    features: ['无广告AI搜索', '自动标注引用来源', '学术文献检索', '深度研究报告模式'],
    howToUse: [
      '访问 metaso.cn，无需注册即可使用',
      '输入搜索问题，选择范围（全网 / 学术 / 社交）',
      '查看 AI 生成的综合答案和引用来源',
      '使用「深度研究」模式生成详细分析报告',
    ],
    faqs: [
      { q: '秘塔AI搜索完全免费吗？', a: '是的，目前完全免费，无广告。' },
      { q: '和普通搜索引擎有什么区别？', a: '秘塔会综合多个来源自动生成答案并标注引用，省去逐个网页阅读的时间。' },
    ],
  },
  // ── 国内图像/视频 AI ──────────────────────────────────────────────────────
  {
    id: 'jimeng-ai',
    name: '即梦AI',
    mono: '梦',
    brand: '#EC4899',
    catId: 'image',
    url: 'https://jimeng.jianying.com',
    en: "ByteDance's Jimeng AI for high-quality image and video generation, tightly integrated with CapCut.",
    zh: '字节跳动推出的AI创作平台，支持文字生成图片和视频，画质精美，与剪映深度集成，创作门槛极低。',
    pricing: 'Freemium',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '每日免费生成次数',
    apiAvailable: false,
    features: ['文字转高质量图片', 'AI视频生成', '多种艺术风格', '剪映生态无缝集成'],
    howToUse: [
      '访问 jimeng.jianying.com，用抖音 / 剪映账号登录',
      '选择「图片生成」或「视频生成」功能',
      '输入中文描述词，选择风格和比例',
      '生成后可直接导入剪映进行视频剪辑',
    ],
    faqs: [
      { q: '即梦 AI 和剪映是什么关系？', a: '两者都是字节跳动旗下产品，即梦专注 AI 内容生成，剪映负责视频剪辑，可无缝配合。' },
      { q: '生成的图片有版权问题吗？', a: '用户对生成内容拥有使用权，商业用途建议查阅最新服务条款。' },
    ],
  },
  {
    id: 'kling-ai',
    name: '可灵AI',
    mono: 'KL',
    brand: '#7C3AED',
    catId: 'video',
    url: 'https://klingai.com',
    en: "Kuaishou's Kling AI video generator producing physics-accurate videos up to 3 minutes from text or images.",
    zh: '快手推出的AI视频生成工具，支持文字和图片转视频，物理效果逼真，最长可生成3分钟高质量视频。',
    pricing: 'Freemium',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '每日免费生成次数',
    apiAvailable: true,
    features: ['最长3分钟AI视频', '图片转视频', '物理动效逼真', '多种运镜模式'],
    howToUse: [
      '访问 klingai.com，注册登录快手账号',
      '选择「文字生成视频」或「图片生成视频」',
      '输入描述词或上传参考图，设置时长和画面比例',
      '等待生成（约 2-5 分钟），下载或继续编辑',
    ],
    faqs: [
      { q: '生成一个视频需要多长时间？', a: '通常 2-5 分钟，高峰期稍长。专业版用户可享受优先排队。' },
      { q: '可灵 AI 有 API 吗？', a: '有，开发者可在 klingai.com/dev 申请 API 接入。' },
    ],
  },
  {
    id: 'hailuo-ai',
    name: '海螺AI',
    mono: '海',
    brand: '#0891B2',
    catId: 'video',
    url: 'https://hailuoai.com',
    en: "MiniMax's Hailuo AI for generating cinematic-quality short videos from text or images.",
    zh: 'MiniMax推出的AI视频生成工具，支持文生视频和图生视频，画面质感电影级，在国际上广受好评。',
    pricing: 'Freemium',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '每日免费生成次数',
    apiAvailable: false,
    features: ['电影级画质视频', '文字/图片转视频', '多种视频风格', '国际化产品体验'],
    howToUse: [
      '访问 hailuoai.com，注册登录',
      '选择视频生成功能，输入场景描述',
      '可上传参考图，选择视频风格',
      '生成完成后预览并下载 MP4',
    ],
    faqs: [
      { q: '海螺 AI 和 MiniMax 是什么关系？', a: '海螺 AI 是 MiniMax 推出的视频生成产品，MiniMax 是背后的 AI 公司。' },
      { q: '生成的视频可以商用吗？', a: '可以，但需遵守平台服务条款，不得用于违法内容。' },
    ],
  },
  {
    id: 'wenshuyige',
    name: '文心一格',
    mono: '格',
    brand: '#7C2D12',
    catId: 'image',
    url: 'https://yige.baidu.com',
    en: "Baidu's ERNIE-ViLG AI image generation tool for creating artistic images from Chinese text prompts.",
    zh: '百度推出的AI绘画工具，基于文心大模型，支持中文描述词生成高质量艺术图片，多种风格可选。',
    pricing: 'Freemium',
    chinaAccess: 'accessible',
    chineseUi: true,
    freeQuota: '每日免费生成次数',
    apiAvailable: false,
    features: ['中文描述词直接生图', '多种艺术风格', '商业级图片质量', '百度账号直接登录'],
    howToUse: [
      '访问 yige.baidu.com，用百度账号登录',
      '在文本框输入中文描述，选择风格和比例',
      '点击生成，等待约 10-30 秒',
      '满意后可直接下载或分享',
    ],
    faqs: [
      { q: '文心一格和 Midjourney 有什么区别？', a: '文心一格支持中文描述词，国内直接访问；Midjourney 需英文提示词且需要 VPN。' },
    ],
  },
];

async function main() {
  console.log(`准备插入 ${CN_TOOLS.length} 个工具...`);
  let inserted = 0;
  let skipped = 0;

  for (const tool of CN_TOOLS) {
    const result = await db.insert(tools).values({
      id: tool.id,
      name: tool.name,
      mono: tool.mono,
      brand: tool.brand,
      catId: tool.catId,
      url: tool.url,
      en: tool.en,
      zh: tool.zh,
      pricing: tool.pricing as 'Free' | 'Freemium' | 'Paid',
      chinaAccess: tool.chinaAccess as 'accessible' | 'vpn-required' | 'blocked' | 'unknown',
      chineseUi: tool.chineseUi ?? false,
      freeQuota: tool.freeQuota ?? null,
      apiAvailable: tool.apiAvailable ?? false,
      openSource: (tool as { openSource?: boolean }).openSource ?? false,
      featured: tool.featured ?? false,
      features: tool.features,
      howToUse: tool.howToUse,
      faqs: tool.faqs,
      publishedAt: TODAY,
    }).onConflictDoNothing();

    if (result.rowCount && result.rowCount > 0) {
      console.log(`  ✅ 已插入: ${tool.name}`);
      inserted++;
    } else {
      console.log(`  ⏭  已存在: ${tool.name}`);
      skipped++;
    }
  }

  console.log(`\n完成：插入 ${inserted} 条，跳过 ${skipped} 条（已存在）`);
  process.exit(0);
}

main().catch((err) => {
  console.error('插入失败:', err);
  process.exit(1);
});
